import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import CommentModal from '../../components/CommentModal'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import Post from '../../components/Post'
import { ArrowLeftIcon } from '@heroicons/react/solid'
import { db } from '../../firebase'
import { doc, onSnapshot } from 'firebase/firestore'

export default function PostPage({ newsResults, randomUsersResults }) {

    const router = useRouter()
    const { id } = router.query
    const [post, setPost] = useState([])

    useEffect(
        () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot))
        , [db, id]
    )

    // get comments

    return (
        <div>
            <Head>
                <title>Post Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex min-h-screen mx-auto">
                {/* Sidebar */}
                <Sidebar />

                {/* Feed */}

                <div className='xl:ml-[370px] border-l border-r xl:min-w-[567px] sm:ml-[73px] flex-grow max-w-xl'>
                    <div className='flex py-2 px-3 sticky top-0 z-50 bg:white border-b border-gray-200 items-center space-x-2'>
                        <div className='hoverEffect' onClick={() => router.push('/')}>
                            <ArrowLeftIcon className='h-5' />
                        </div>
                        <h2 className='text-lg sm:text-xl font-bold'>
                            Tweet
                        </h2>
                    </div>

                    <Post id={id} post={post} />

                    {/* Comments */}
                </div>

                {/* Widgets */}

                <Widgets
                    newsResults={newsResults.articles}
                    randomUsersResults={randomUsersResults.results}
                />

                {/* Modal */}

                <CommentModal />
            </main>
        </div>
    )
}

export async function getServerSideProps() {
    const newsResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/health/in.json')
        .then((res) => res.json());

    // Who to follow
    const randomUsersResults = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture')
        .then((res) => res.json());
    return {
        props: {
            newsResults,
            randomUsersResults,
        },
    };
}